// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1gVESDFQRJtqlfT_oydRHdsTn4M5DiE',
    appId: '1:1021387950803:web:a289094cfe89a923dbe226',
    messagingSenderId: '1021387950803',
    projectId: 'instalive-b0578',
    authDomain: 'instalive-b0578.firebaseapp.com',
    storageBucket: 'instalive-b0578.firebasestorage.app',
    measurementId: 'G-LFH75YSZRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_AgFreaUjzmt9HRXrEWC5ropnxo2rrDY',
    appId: '1:1021387950803:android:f6117347e4ada31fdbe226',
    messagingSenderId: '1021387950803',
    projectId: 'instalive-b0578',
    storageBucket: 'instalive-b0578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aN1Ep4BLtEqUPRkgEPvKUUgbM_rV8-I',
    appId: '1:1021387950803:ios:fbccc20de374357bdbe226',
    messagingSenderId: '1021387950803',
    projectId: 'instalive-b0578',
    storageBucket: 'instalive-b0578.firebasestorage.app',
    iosBundleId: 'com.instalive.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aN1Ep4BLtEqUPRkgEPvKUUgbM_rV8-I',
    appId: '1:1021387950803:ios:fbccc20de374357bdbe226',
    messagingSenderId: '1021387950803',
    projectId: 'instalive-b0578',
    storageBucket: 'instalive-b0578.firebasestorage.app',
    iosBundleId: 'com.instalive.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1gVESDFQRJtqlfT_oydRHdsTn4M5DiE',
    appId: '1:1021387950803:web:1747edb91445e731dbe226',
    messagingSenderId: '1021387950803',
    projectId: 'instalive-b0578',
    authDomain: 'instalive-b0578.firebaseapp.com',
    storageBucket: 'instalive-b0578.firebasestorage.app',
    measurementId: 'G-T87N7QP1BN',
  );
}
